# Generated by Django 4.2.6 on 2023-10-11 23:04

import car_app.models
from django.db import migrations, models
import django_dataclass_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_data",
                    django_dataclass_field.fields.DataClassField(
                        data_class=car_app.models.Car
                    ),
                ),
            ],
        ),
    ]
